blank_issues_enabled: true
contact_links:
  - name: 📚 Nuxt Reapit Documentation
    url: https://github.com/johannschopplich/nuxt-reapit#readme
    about: Check the documentation for usage of Nuxt Reapit
